[package]
name = "nccl-net-homa"
version = "0.1.0"
edition = "2021"

[dependencies]
nccl-net-sys = { path = "../nccl-net-sys" }
roma = { path = "../roma" }
socket2 = "0.5.1"
if-addrs = "0.10.1"
log = "0.4.17"
thiserror = "1.0.39"

[lib]
crate-type = ["cdylib", "lib"]
